apiVersion: v1
kind: ConfigMap
metadata:
  name: cache-cfgmp
  namespace: dictionary
data:
  redis.conf: |
    daemonize no
    pidfile /var/run/redis_6379.pid
    logfile "redis_6379.log"
    requirepass redis666
    bind * -::*
